### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Armandeus66** [paulo-roger/flying-tokens#5]
Using Foundry v 10.286 and Pathfinder 2E v4.1.3, I get these console errors when giving a familiar with flying movement a 5 foot elevation. (Flying effects are also not being applied.)

commons.js:1696 Error: You are accessing the FamiliarPF2e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1685:19)
    at FamiliarPF2e._logV10CompatibilityWarning (commons.js:6612:14)
    at get data [as data] (commons.js:6512:24)
    at isFlyer (flying-tokens.js:45:32)
    at FlyingHud.renderHud (flying-hud.js:20:13)
    at Object.fn (flying-tokens.js:40:19)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenHUD._render (foundry.js:5112:13)
    at async TokenHUD._render (foundry.js:67812:5)
logCompatibilityWarning @ commons.js:1696
commons.js:1696 Error: You are accessing FamiliarPF2e#data which has been migrated to FamiliarPF2e#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1685:19)
    at FamiliarPF2e._logDataFieldMigration (commons.js:6601:14)
    at Object.get (commons.js:6565:18)
    at isFlyer (flying-tokens.js:45:37)
    at FlyingHud.renderHud (flying-hud.js:20:13)
    at Object.fn (flying-tokens.js:40:19)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenHUD._render (foundry.js:5112:13)
    at async TokenHUD._render (foundry.js:67812:5)
logCompatibilityWarning @ commons.js:1696
flying-tokens.js:45 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fly')
[Detected 1 package: flying-tokens]
    at isFlyer (flying-tokens.js:45:62)
    at FlyingHud.renderHud (flying-hud.js:20:13)
    at Object.fn (flying-tokens.js:40:19)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenHUD._render (foundry.js:5112:13)
    at async TokenHUD._render (foundry.js:67812:5)

**Comment by paulo-roger** [comment]
Thanks for the report, I will add compatibility with PF2E.

**Comment by paulo-roger** [comment]
Added in the new version
https://github.com/LeafWulf/flying-tokens
